add helpful messages to setup-*-env scripts

diff --git a/fornax-base/scripts/setup-conda-env b/fornax-base/scripts/setup-conda-env
--- a/fornax-base/scripts/setup-conda-env
+++ b/fornax-base/scripts/setup-conda-env
@@ -1,11 +1,15 @@
 #!/bin/bash
-
 # handle conda environment and lock files
 # look for conda-{env}-lock.yml and conda-{env}.yml files
 
-# exit on failure; print commands
-set -ex
+# exit on failure
+set -e
 set -o pipefail
+
+echo
+echo "  Setup conda-based python environment using micromamba, along with the notebook kernel."
+echo "  For help, see: $0 -h"
+echo
 
 # envdir: where to install the new environment
 # if not given, default to ENV_DIR
@@ -18,7 +22,6 @@ elif [[ "$arg" == "--user" ]]; then
 
 elif [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
     echo "
-    Setup conda-based python environment using micromamba, along with the notebook kernel.
 
     USAGE:
     -----
diff --git a/fornax-base/scripts/setup-pip-env b/fornax-base/scripts/setup-pip-env
--- a/fornax-base/scripts/setup-pip-env
+++ b/fornax-base/scripts/setup-pip-env
@@ -2,9 +2,14 @@
 # Handle uv environment
 # Creates an environment for every requirements-{env-name}.txt file
 
-# exit on failure; print commands
-set -ex
+# exit on failure
+set -e
 set -o pipefail
+
+echo
+echo "  Setup pip-based python environment using uv, along with the notebook kernel."
+echo "  For help, see: $0 -h"
+echo
 
 # emvdir: where to install the new environment
 # if not given, default to ENV_DIR
@@ -16,8 +21,7 @@ elif [[ "$arg" == "--user" ]]; then
     envdir=$USER_ENV_DIR
 
 elif [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
-    echo "
-    Setup pip-based python environment using uv, along with the notebook kernel.
+    echo """
 
     USAGE:
     -----
@@ -31,7 +35,7 @@ elif [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
     
     Activate with: source \$ENV_DIR/{env_name}/bin/activate 
         (or source \$USER_ENV_DIR/{env_name}/bin/activate if you passed --user)
-"
+"""
     exit 0
 else
     echo "Unknown argument $1"
